-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID 
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(*) AS CNT
      FROM ONLINE_SALE
      GROUP BY USER_ID, PRODUCT_ID) AS SUB -- GROUP BY USERID,PRODUCT_ID 를 통해 '동일한 유저' 가 '같은 상품' 에 대해 구매한 케이스를 구분
WHERE CNT > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;